package sollecitom.services.modulith_example.service.test.security

import sollecitom.libs.swissknife.security.scan.ImageSecurityScanTestSpecification

class ServiceImageSecurityScanTests : ImageSecurityScanTestSpecification
